import Head from "next/head";
import { Inter } from "@next/font/google";
import { useEffect, useState } from "react";
import Link from "next/link";
import Image from "next/image";
import { Pokemon } from "../utils/types";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [pokemon, setPokemon] = useState<Pokemon[]>([]);

  useEffect(() => {
    async function getPokemon() {
      const res = await fetch(
        "https://jherr-pokemon.s3.us-west-1.amazonaws.com/index.json"
      );
      setPokemon(await res.json());
    }
    getPokemon();
  }, []);
  return (
    <div className="mx-5">
      <Head>
        <title>Pokemon List</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="grid grid-cols-5 gap-12">
        {pokemon.map((pokemon) => (
          <div
            key={pokemon.id}
            className="flex flex-col items-center border-2 border-gray-400 rounded-lg p-4"
          >
            <Link href={`/pokemon/${pokemon.id}`}>
              <Image
                src={`https://jherr-pokemon.s3.us-west-1.amazonaws.com/${pokemon.image}`}
                alt={pokemon.name}
                width={200}
                height={200}
                className="h-52 w-40 object-contain"
              />
            </Link>
            <h3>{pokemon.name}</h3>
          </div>
        ))}{" "}
      </div>
    </div>
  );
}
